### PR TITLE
update TestPrecompute to modern standards

### PR DESCRIPTION
**Pull request by hampgoodwin**
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestPrecompute$ github.com/moov-io/watchman/cmd/server

ok  	github.com/moov-io/watchman/cmd/server	0.175s
```

### CODE REVIEW

**Review by adamdecaf — APPROVED** [review]
Thanks for updating this!

**Comment by adamdecaf** [comment]
@hampgoodwin can you rebase off `origin/master`? Fixed the build.

**Comment by hampgoodwin** [comment]
Looks like there's a build failure. From what I can tell when attempting to build watchman (and then test?), the port 8084 is already occupied somewhere in the CI process.

Any suggestions on where I can look to fix this? I already tried some of the usual culprits I would expect, like a bad config in docker-compose, two services same port or something, but I didn't find anything obvious to me.

https://github.com/moov-io/watchman/pull/335/checks?check_run_id=2229796797

**Comment by adamdecaf** [comment]
Yea. That looks to be an issue with conflicting ports. Not sure why, but there must be something that didn't shutdown properly before.

**Comment by hampgoodwin** [comment]
> Yea. That looks to be an issue with conflicting ports. Not sure why, but there must be something that didn't shutdown properly before.

I did try a simple "re-run tests" before my comment, and it was the same thing. When you say "something that didn't shutdown properly before", do you mean in a previous run, or in the same run? I'll look around the makefile to see what all is ran and try to validate there should be no port conflicts.

**Comment by adamdecaf** [comment]
> do you mean in a previous run, or in the same run? 

I'm not sure off hand. Would need to look into it. There's likely stuff we can optimize from the past year or two.

**Comment by hampgoodwin** [comment]
Ok,
So to me this sounds like an invitation to look at the build process, and make whatever changes I would consider a standard build.
I'll do this with a branch that I'll PR into this branch & PR.
Thanks! :)

**Comment by adamdecaf** [comment]
Can we rebase this off `origin/master`?

**Review by adamdecaf — APPROVED** [review]

**Pull request merged**
