### PR TITLE
Add support for Postgres in watchman.

### PR DESCRIPTION
**Pull request by swhyte-rt**
Added Postgres support in watchman. I did move out the repository code (customer, company, download, web hook and watch) to their own files so that they would be self contained and hold the various differences between generic SQL DB like SQLite and MySQL and Postgres. I also changed the sqlite<repository name>repository to generic<repository name>repository for clarity. I added multiple tests to exercise the most recent minor version of Postgres from 10 through 12.

### CODE REVIEW

**Comment by adamdecaf** [comment]
Thanks Stephen! Looking at the changes this makes I want to try out https://gorm.io/ on this branch. I think that'll help reduce the clutter. Having the separate queries I think will work, but isn't ideal. I'm going to branch from here and try it out.

**Comment by swhyte-rt** [comment]
> Thanks Stephen! Looking at the changes this makes I want to try out https://gorm.io/ on this branch. I think that'll help reduce the clutter. Having the separate queries I think will work, but isn't ideal. I'm going to branch from here and try it out.

@adamdecaf That sounds good.

**Comment by adamdecaf** [comment]
The tests are failing from `dbType` being a global variable. Could we store that on the `genericSQLRepository`?

**Comment by swhyte-rt** [comment]
> The tests are failing from `dbType` being a global variable. Could we store that on the `genericSQLRepository`?

Yes that would work.

**Comment by adamdecaf** [comment]
GORM looks nice, but we'd have to convert the project over to it. Thoughts @swhyte-rt ? It would allow us one repo for all databases.

**Comment by adamdecaf** [comment]
I noticed some tests are failing from `dbType` it appears

```
--- FAIL: TestWebhook_record (17.61s)
    webhook_test.go:157: Error 1054: Unknown column '$1' in 'field list'
```

**Comment by swhyte-rt** [comment]
> GORM looks nice, but we'd have to convert the project over to it. Thoughts @swhyte-rt ? It would allow us one repo for all databases.

@adamdecaf I agree, using GORM would allow us to abstract the underlying implementation, and have just one repo. I will do a bit of reading on GORM and can assist.

**Comment by swhyte-rt** [comment]
> I noticed some tests are failing from `dbType` it appears
> 
> ```
> --- FAIL: TestWebhook_record (17.61s)
>     webhook_test.go:157: Error 1054: Unknown column '$1' in 'field list'
> ```

I think that moving dbType to repo will fix it, but if we want to use GORM it will look after it for us.

**Pull request closed without merging**
