### PR TITLE
add metrics for customer/company active watch

### LINKED ISSUE #236: metrics: expose active watch counts
It seems useful to expose the number of active customer and company watches as a metric. This would help inspect the load as more watches are re-searched.

- company and company name watches
- customer and customer name watches

### PR DESCRIPTION
**Pull request by tharun208**
This patch introduces metrics for active `company` and `customer` watches.

Resolves #236

### CODE REVIEW

**Comment by adamdecaf** [comment]
Thanks for the PR! This works to count the watches created when Watchman is running, but doesn't include the counts in the database. Shouldn't we include those as well?

**Comment by tharun208** [comment]
can we do that as a separate pr because we don't have metrics for the DB layer?

**Comment by adamdecaf** [comment]
@tharun208 yea, but can we rename these? Something like `created_customer_watches_count`?

**Comment by tharun208** [comment]
> @tharun208 yea, but can we rename these? Something like `created_customer_watches_count`?

but, this is for the active customer/company watch `created_customer_watches_count` seems to be a bit misleading metric name. WDYT?

**Comment by adamdecaf** [comment]
I'd call "active" to be the count of watches in the database that Watchman cares about. These counts are only "watches created by this instance since it started." 

If you're running two Watchman instances (w1, w2) then these metrics would be different between w1 and w2 depending on which ones behind the load balancer received the POST/DELETE requests.

**Pull request closed without merging**
